sudo: required
install:
- sudo apt-get update
- sudo apt-get install texlive texlive-lang-cyrillic cm-super lmodern pandoc

jobs:
  include:
  - stage: "Generate pdf files"
    script: pandoc -o Aremiy_Rodionov_CV.pdf README.md
    script: pandoc -s -o Aremiy_Rodionov_CV.ru.pdf README.ru.md
    deploy:
      provider: releases
      api_key:
        secure: r/EIwYZjaSQjLcRkmuC2D7DfaqFFmkPztAJoHYClN/ntBhD8ksFzrhr87rN7mXE/9HzTS1L0/LudaSUxz9c8oViVlfBRmpNSV+OWVkLAZvpY/tPi18v+/dKOzY7GsTILLro9qxxmq/Avou762qrNokfVFuD3jqD4IlG0GeIqksWKYQIgiasPKfUX5zKbRKhMtAP0xOK4aWF0yMivrQkf1X8dDKRcJJ3Jp2AefXKMRKv4XUBcHhLUFLbv1qwNjzLbc7B/Coq7YYlOLP04bkUrAZZHMhni1cP6LDAL5KNzJb372LIgGmPzlvHj4M9L+tjsNu0QLbUEf3m90sqpUniApHWi6l5OWNUbJDcaquVRW53v0nYiW5wLVrzDc419k74+ovgqPsLdyyr5qePybqymCUAb6kOYRDBOPEqgLHZVSn4KhliN0lulsVS0AtkknyWSVepoq4dvR7w/UFaA45ZgOQo1kUMy1ddZ4/OUw/AZkLaW8nDsGHAtxlLCZ2GMqgfljqhbZCNlG3P3CXWg7epQ6HozU5BoKWOe6h0qHF+dnwk51yibU7u0+hK+E0o6YAnMoOPNaEAQrGcQavQS35qx8cWFQNrHBbva48TbUswsGKJtutTnyNQVYwRXwBSSi3rg5dXIccXtXxzBKLiTcilhc1U2MHVxsn9j8bqn7NFT61E=
      skip_cleanup: true
      file:
      - Aremiy_Rodionov_CV.pdf
      - Aremiy_Rodionov_CV.ru.pdf
      on:
        tags: true
        branch: master
        repo: artemiy312/CV
